const express = require('express');
const router = express.Router();
const User = require('../models/User');
const ResourceRequest = require('../models/ResourceRequest');
const auth = require('../middleware/auth');

// Create a new resource request
router.post('/', auth, async (req, res) => {
  try {
    console.log('Received request body:', req.body);
    const { items } = req.body;

    if (!items || !Array.isArray(items) || items.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Request must include at least one item'
      });
    }

    // Get the requesting user's details
    console.log('Finding requesting user with ID:', req.user._id);
    const requestingUser = await User.findById(req.user._id);
    
    if (!requestingUser) {
      console.error('Requesting user not found:', req.user._id);
      return res.status(404).json({
        success: false,
        message: 'Requesting user not found'
      });
    }

    console.log('Found requesting user:', {
      id: requestingUser._id,
      department: requestingUser.department,
      role: requestingUser.role
    });

    // Find the department head
    console.log('Finding department head for department:', requestingUser.department);
    const departmentHead = await User.findOne({
      department: requestingUser.department,
      role: 'department_head',
      status: 'approved'
    }).select('_id fullName department role');

    if (!departmentHead) {
      console.error('No department head found for department:', requestingUser.department);
      return res.status(400).json({
        success: false,
        message: `No approved department head found for ${requestingUser.department}. Please contact system administrator.`
      });
    }

    console.log('Found department head:', {
      id: departmentHead._id,
      department: departmentHead.department,
      role: departmentHead.role
    });

    // Request number will be auto-generated by the schema's pre-save hook

    const currentDate = new Date();
    
    // Create the resource request
    const resourceRequest = new ResourceRequest({
      requestedBy: req.user._id,
      division: requestingUser.department,
      requestedItems: items.map(item => ({
        resource: item.resource,  // Resource ID is required
        itemNo: item.itemNo,
        description: item.description,
        unitOfMeasure: item.unitOfMeasure,
        quantityRequested: parseInt(item.quantityRequested) || 1,
        unitPrice: {
          birr: parseInt(item.price?.birr) || 0,
          cents: parseInt(item.price?.cents) || 0
        },
        totalAmount: {
          birr: parseInt(item.totalAmount?.birr) || 0,
          cents: parseInt(item.totalAmount?.cents) || 0
        },
        remark: item.remarks || ''
      })),
      status: 'pending',
      requestedDivisionHead: {
        name: departmentHead.fullName || '',
        date: currentDate,
        signature: ''
      },
      requestedAndReceivedBy: {
        name: requestingUser.fullName || '',
        date: currentDate,
        signature: ''
      },
      certifiedBy: {
        name: departmentHead.fullName || '',
        date: currentDate,
        signature: ''
      },
      assignedTo: {
        userId: departmentHead._id,
        name: departmentHead.fullName || '',
        role: 'department_head'
      }
    });

    try {
      console.log('Attempting to save resource request...');
      const savedRequest = await resourceRequest.save();
      console.log('Resource request saved successfully:', savedRequest._id);

      // Populate necessary fields for response
      const populatedRequest = await ResourceRequest.findById(savedRequest._id)
        .populate('requestedBy', 'fullName department')
        .populate('assignedTo.userId', 'fullName department role');

      res.status(201).json({
        success: true,
        message: 'Resource request created successfully',
        data: populatedRequest
      });
    } catch (error) {
      console.error('Error details:', {
        name: error.name,
        message: error.message,
        stack: error.stack
      });

      if (error.name === 'ValidationError') {
        const validationErrors = Object.values(error.errors).map(err => ({
          field: err.path,
          message: err.message,
          value: err.value
        }));
        console.error('Validation errors:', validationErrors);
        
        return res.status(400).json({
          success: false,
          message: 'Validation error',
          errors: validationErrors
        });
      }

      res.status(500).json({
        success: false,
        message: 'Error creating resource request',
        error: error.message
      });
    }
  } catch (error) {
    console.error('Unhandled error in request creation:', {
      name: error.name,
      message: error.message,
      stack: error.stack
    });

    res.status(500).json({
      success: false,
      message: 'Error creating resource request',
      error: error.message
    });
  }
});

// Get resource requests with filtering
router.get('/', auth, async (req, res) => {
  try {
    const { status } = req.query;
    const filter = {};

    // If user is department head, only show requests from their department
    if (req.user.role === 'department_head') {
      filter['division'] = req.user.department;
      filter['assignedTo.userId'] = req.user._id;
    } else if (req.user.role === 'staff') {
      // Staff can only see their own requests
      filter['requestedBy'] = req.user._id;
    }

    // Add status filter if provided
    if (status) {
      filter.status = status;
    }

    const requests = await ResourceRequest.find(filter)
      .populate('requestedBy', 'fullName department')
      .sort({ 'requestedDivisionHead.date': -1 })
      .select('-__v')
      .lean();

    res.json({
      success: true,
      data: requests
    });
  } catch (error) {
    console.error('Error fetching requests:', error);
    res.status(500).json({ 
      success: false,
      message: 'Error fetching resource requests' 
    });
  }
});

// Get resource requests for a user
router.get('/my-requests', auth, async (req, res) => {
  try {
    const requests = await ResourceRequest.find({
      'requestedBy.userId': req.user._id
    }).sort({ requestDate: -1 });

    res.json({
      success: true,
      requests
    });
  } catch (error) {
    console.error('Error fetching resource requests:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching resource requests'
    });
  }
});

// Get requests assigned to a department head
router.get('/assigned-requests', auth, async (req, res) => {
  try {
    // Verify user is a department head
    if (req.user.role !== 'department_head') {
      return res.status(403).json({
        success: false,
        message: 'Access denied. Only department heads can view assigned requests.'
      });
    }

    const requests = await ResourceRequest.find({
      'assignedTo.userId': req.user._id
    }).sort({ requestDate: -1 });

    res.json({
      success: true,
      requests
    });
  } catch (error) {
    console.error('Error fetching assigned requests:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching assigned requests'
    });
  }
});

module.exports = router;
